# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20190723_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
