# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0005_auto_20190723_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
