# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0006_auto_20190723_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
